### ISSUE TITLE
Consumer

### ISSUE THREAD

**Issue by Makashima** [Fresa/Kafka.TestFramework#1]
Would be useful to provide a consumerbuiler example in the tests

**Comment by Fresa** [comment]
Good point, I will add that when I have some spare time!

**Comment by Fresa** [comment]
I've added a broker [consumer scenario](https://github.com/Fresa/Kafka.TestFramework/blob/a935148a55bba577404f548edd05dfe7294519f7/tests/Kafka.TestFramework.Tests/Given_a_socket_based_test_server.When_connecting_to_the_server_and_consuming_a_message.cs) which orchestrates a [confluent-kafka-dotnet](https://github.com/confluentinc/confluent-kafka-dotnet)'s consumer.
